name: Bundle Size Report

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Analyze Bundle
        run: npm run build && npx size-limit --json > size.json

      - name: Comment Bundle Size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


# > Add "size-limit" to devDependencies and "size-limit": [...] in your package.json
