# All-in-one *modular universal workflow*: linting, type-checks, tests, build, deploy, and team integrations — all with smart conditionals & caching.


name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node + Cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: runner.os -node-{{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 3. Install deps
      - name: Install Dependencies
        run: npm ci

      # 4. Lint
      - name: Lint
        run: npm run lint

      # 5. Format Check
      - name: Prettier Format Check
        run: npm run format:check

      # 6. Type Check
      - name: TypeScript Check
        run: npm run typecheck

      # 7. Tests (skip if docs only)
      - name: Run Tests
        if: "!contains(github.event.head_commit.message, '[skip tests]')"

     run: npm test

      # 8. Build Verification
      - name: Build App
        run: npm run build

      # 9. Deploy on main only
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: npx vercel –prod –token={{ secrets.VERCEL_TOKEN }}

      # 10. Slack Notification
      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: job.status
          fields: repo,message,commit,author,job,took
        env:
          SLACK_WEBHOOK_URL:{{ secrets.SLACK_WEBHOOK_URL }}

      # 11. Update Linear (if integrated)
      - name: Linear Auto Link
        if: github.event_name == 'pull_request'
        uses: nearform/linear-auto-link@v1
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}


# *Notes:*
# - `npm run format:check` should run `prettier --check .`
# - `VERCEL_TOKEN`, `SLACK_WEBHOOK_URL`, and `LINEAR_API_KEY` must be in repo secrets
# - Easy to adapt for `yarn` or `pnpm`
# - You can skip tests via commit message like: `fix: typo [skip tests]`
