name: Generate Docs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm ci

      - name: Generate Docs
        run: npm run docs && git add docs && git commit -m "update docs" && git push
