# ✅ Type Check Workflow
# Ensures your TypeScript codebase has no type errors on push and PR

name: Type Check

on:
  push:
    branches: [main]  # 👈 Change to ["*"] for all branches, or add more like [main, dev]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      # 🧾 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 🧰 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Match your dev environment

      # 📦 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 🧠 4. Run TypeScript type check
      - name: Type check
        run: npx tsc --noEmit  # 🚫 noEmit = don’t output .js files, just check types


# ensure you have typescript installed
# npm i -D typescript
